/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cablebillmanagement;

/**
 *
 * @author Jaideep
 */
public class UpdateDeleteWindow extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDeleteWindow
     */
    public UpdateDeleteWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminUpdateDelete = new javax.swing.JPanel();
        pendingRequest = new javax.swing.JPanel();
        UserUpdateDelete = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        AdminUpdateDelete.setBackground(new java.awt.Color(125, 159, 154));
        AdminUpdateDelete.setLayout(new javax.swing.OverlayLayout(AdminUpdateDelete));

        pendingRequest.setBackground(new java.awt.Color(125, 159, 154));

        javax.swing.GroupLayout pendingRequestLayout = new javax.swing.GroupLayout(pendingRequest);
        pendingRequest.setLayout(pendingRequestLayout);
        pendingRequestLayout.setHorizontalGroup(
            pendingRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        pendingRequestLayout.setVerticalGroup(
            pendingRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        AdminUpdateDelete.add(pendingRequest);

        getContentPane().add(AdminUpdateDelete);

        UserUpdateDelete.setBackground(new java.awt.Color(125, 159, 154));

        javax.swing.GroupLayout UserUpdateDeleteLayout = new javax.swing.GroupLayout(UserUpdateDelete);
        UserUpdateDelete.setLayout(UserUpdateDeleteLayout);
        UserUpdateDeleteLayout.setHorizontalGroup(
            UserUpdateDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        UserUpdateDeleteLayout.setVerticalGroup(
            UserUpdateDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        getContentPane().add(UserUpdateDelete);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminUpdateDelete;
    private javax.swing.JPanel UserUpdateDelete;
    private javax.swing.JPanel pendingRequest;
    // End of variables declaration//GEN-END:variables
}
