/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cablebillmanagement;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jaideep
 */
public class UserMainUI extends javax.swing.JFrame {

    /**
     * Creates new form UserMainUI
     */
    public UserMainUI() {
        initComponents();
        changeTOBtnDefaultColor();
        highlightClicked(subscriptionPlansJPanel, subscriptionPlansTextjLabel);
    }
    
    //    changing menu button to default color
    private void changeTOBtnDefaultColor(){
//        changing bg color
        subscriptionPlansJPanel.setBackground(new Color(61,81,85));
        pendingPaymentJPanel.setBackground(new Color(61,81,85));
        billingHistoryJPanel.setBackground(new Color(61,81,85));
        userComplaintsJPanel.setBackground(new Color(61,81,85));
//        changing font colr
        subscriptionPlansTextjLabel.setForeground(new Color(255,255,255));
        pendingPaymentTextjLabel.setForeground(new Color(255,255,255));
        billingHistoryTextjLabel.setForeground(new Color(255,255,255));
        userComplaintsTextjLabel.setForeground(new Color(255,255,255));
    }
    
//    changing menu color to make highlight clicked button
//    and will change Heading text to clicked item
    private void highlightClicked(JPanel clickPanel,JLabel clickLable){
        clickPanel.setBackground(new Color(125,159,154));
        clickLable.setForeground(new Color(21,49,63));
        headingOfPagejLabel.setText(clickLable.getText());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelUserName = new javax.swing.JLabel();
        subscriptionPlansJPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subscriptionPlansTextjLabel = new javax.swing.JLabel();
        pendingPaymentJPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pendingPaymentTextjLabel = new javax.swing.JLabel();
        billingHistoryJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        billingHistoryTextjLabel = new javax.swing.JLabel();
        userComplaintsJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userComplaintsTextjLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        headingOfPagejLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cable Bill Management - User");

        jPanel4.setBackground(new java.awt.Color(20, 33, 48));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 583));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cablebillmanagement/assets/icons8_user_100px_1.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 90));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 176, 22));

        jLabelUserName.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(222, 210, 181));
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Jaideep");
        jPanel4.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 29));

        subscriptionPlansJPanel.setBackground(new java.awt.Color(125, 159, 154));
        subscriptionPlansJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(125, 159, 154)));
        subscriptionPlansJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subscriptionPlansJPanelMouseClicked(evt);
            }
        });
        subscriptionPlansJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cablebillmanagement/assets/icons8_new_letter_24px.png"))); // NOI18N
        subscriptionPlansJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        subscriptionPlansTextjLabel.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        subscriptionPlansTextjLabel.setForeground(new java.awt.Color(21, 49, 63));
        subscriptionPlansTextjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subscriptionPlansTextjLabel.setText("Subscription Plans");
        subscriptionPlansJPanel.add(subscriptionPlansTextjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 20));

        jPanel4.add(subscriptionPlansJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 40));

        pendingPaymentJPanel.setBackground(new java.awt.Color(61, 81, 85));
        pendingPaymentJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(125, 159, 154)));
        pendingPaymentJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingPaymentJPanelMouseClicked(evt);
            }
        });
        pendingPaymentJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cablebillmanagement/assets/icons8_payment_history_24px.png"))); // NOI18N
        pendingPaymentJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        pendingPaymentTextjLabel.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        pendingPaymentTextjLabel.setForeground(new java.awt.Color(255, 255, 255));
        pendingPaymentTextjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pendingPaymentTextjLabel.setText("Pending payment");
        pendingPaymentJPanel.add(pendingPaymentTextjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 20));

        jPanel4.add(pendingPaymentJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        billingHistoryJPanel.setBackground(new java.awt.Color(61, 81, 85));
        billingHistoryJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(125, 159, 154)));
        billingHistoryJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billingHistoryJPanelMouseClicked(evt);
            }
        });
        billingHistoryJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cablebillmanagement/assets/icons8_transaction_24px.png"))); // NOI18N
        billingHistoryJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        billingHistoryTextjLabel.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        billingHistoryTextjLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingHistoryTextjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        billingHistoryTextjLabel.setText("Billing History");
        billingHistoryJPanel.add(billingHistoryTextjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 20));

        jPanel4.add(billingHistoryJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 40));

        userComplaintsJPanel.setBackground(new java.awt.Color(61, 81, 85));
        userComplaintsJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(125, 159, 154)));
        userComplaintsJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userComplaintsJPanelMouseClicked(evt);
            }
        });
        userComplaintsJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cablebillmanagement/assets/icons8_complaint_24px_1.png"))); // NOI18N
        userComplaintsJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        userComplaintsTextjLabel.setFont(new java.awt.Font("Goudy Old Style", 1, 15)); // NOI18N
        userComplaintsTextjLabel.setForeground(new java.awt.Color(255, 255, 255));
        userComplaintsTextjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userComplaintsTextjLabel.setText("Complaints");
        userComplaintsJPanel.add(userComplaintsTextjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 20));

        jPanel4.add(userComplaintsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 40));

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(29, 50, 73));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(103, 156, 181));
        jButton1.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(222, 210, 181));
        jButton1.setText("Log Out");
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 100, 40));

        headingOfPagejLabel.setFont(new java.awt.Font("Goudy Old Style", 0, 48)); // NOI18N
        headingOfPagejLabel.setForeground(new java.awt.Color(222, 210, 181));
        headingOfPagejLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headingOfPagejLabel.setText("Pending Request");
        jPanel1.add(headingOfPagejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 410, 60));

        jPanel5.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(125, 159, 154));
        jPanel2.setAlignmentX(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subscriptionPlansJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subscriptionPlansJPanelMouseClicked
        // TODO add your handling code here:
        changeTOBtnDefaultColor();
        highlightClicked(subscriptionPlansJPanel, subscriptionPlansTextjLabel);

    }//GEN-LAST:event_subscriptionPlansJPanelMouseClicked

    private void pendingPaymentJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingPaymentJPanelMouseClicked
        // TODO add your handling code here:
        changeTOBtnDefaultColor();
        highlightClicked(pendingPaymentJPanel , pendingPaymentTextjLabel);
    }//GEN-LAST:event_pendingPaymentJPanelMouseClicked

    private void billingHistoryJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingHistoryJPanelMouseClicked
        // TODO add your handling code here:
        changeTOBtnDefaultColor();
        highlightClicked(billingHistoryJPanel, billingHistoryTextjLabel);
    }//GEN-LAST:event_billingHistoryJPanelMouseClicked

    private void userComplaintsJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userComplaintsJPanelMouseClicked
        // TODO add your handling code here:
        changeTOBtnDefaultColor();
        highlightClicked(userComplaintsJPanel, userComplaintsTextjLabel);
    }//GEN-LAST:event_userComplaintsJPanelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billingHistoryJPanel;
    private javax.swing.JLabel billingHistoryTextjLabel;
    private javax.swing.JLabel headingOfPagejLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pendingPaymentJPanel;
    private javax.swing.JLabel pendingPaymentTextjLabel;
    private javax.swing.JPanel subscriptionPlansJPanel;
    private javax.swing.JLabel subscriptionPlansTextjLabel;
    private javax.swing.JPanel userComplaintsJPanel;
    private javax.swing.JLabel userComplaintsTextjLabel;
    // End of variables declaration//GEN-END:variables
}
